run:
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - typecheck
    - unconvert
    - unused

issues:
  exclude-use-default: false

linters-settings:
  goimports:
    local-prefixes: github.com/bluekeyes/go-gitdiff
  revive:
    rules:
      # enable all rules from golint
      - name: context-keys-type
      - name: time-naming
      - name: var-declaration
      - name: unexported-return
      - name: errorf
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
