run:
  tests: false

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - govet
    - ineffassign
    - misspell
    - typecheck
    - unconvert
    - varcheck

issues:
  exclude-use-default: false

linters-settings:
  goimports:
    local-prefixes: github.com/bluekeyes/go-gitdiff
  errcheck:
    exclude-functions:
      - (*github.com/bluekeyes/go-gitdiff/gitdiff.formatter).Write
      - (*github.com/bluekeyes/go-gitdiff/gitdiff.formatter).WriteString
      - (*github.com/bluekeyes/go-gitdiff/gitdiff.formatter).WriteByte
      - fmt.Fprintf(*github.com/bluekeyes/go-gitdiff/gitdiff.formatter)
