//go:build ignore

// bin.go is a helper CLI to manipulate binary diff data for testing purposes.
// It can decode patches generated by git using the standard parsing functions
// or it can encode binary data back into the format expected by Git. It
// operates on stdin and writes results (possibly binary) to stdout.

package main

import (
	"bytes"
	"compress/zlib"
	"encoding/hex"
	"flag"
	"io"
	"log"
	"os"
	"unicode"

	"github.com/bluekeyes/go-gitdiff/gitdiff"
)

var mode string
var compression bool
var hexInput bool
var method string

func compress(data []byte) ([]byte, error) {
	var b bytes.Buffer
	w := zlib.NewWriter(&b)

	if _, err := w.Write(data); err != nil {
		return nil, err
	}
	if err := w.Close(); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func init() {
	flag.StringVar(&mode, "mode", "parse", "operation mode, one of 'parse' or 'encode'")
	flag.BoolVar(&compression, "compression", true, "if true, decompress data in 'parse' mode and compress it in 'encode' mode")
	flag.BoolVar(&hexInput, "hex", false, "in encode mode, treat the input as a hexidecimal string (removing whitespace and comments)")
	flag.StringVar(&method, "method", "literal", "in encode mode, the method of the binary fragment, one of 'literal' or 'delta'")
}

func main() {
	flag.Parse()

	switch mode {
	case "parse":
		files, _, err := gitdiff.Parse(os.Stdin)
		if err != nil {
			log.Fatalf("failed to parse file: %v", err)
		}
		if len(files) != 1 {
			log.Fatalf("patch contains more than one file: %d", len(files))
		}

		frag := files[0].BinaryFragment
		if frag == nil {
			log.Fatalf("patch file does not contain a binary fragment")
		}
		if compression {
			data, err := io.ReadAll(frag.Data())
			if err != nil {
				log.Fatalf("patch file contains invalid binary data: %v", err)
			}
			os.Stdout.Write(data)
		} else {
			os.Stdout.Write(frag.RawData)
		}

	case "encode":
		var frag gitdiff.BinaryFragment
		switch method {
		case "literal":
			frag.Method = gitdiff.BinaryPatchLiteral
		case "delta":
			frag.Method = gitdiff.BinaryPatchDelta
		default:
			log.Fatalf("invalid method: %s", method)
		}

		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			log.Fatalf("failed to read input: %v", err)
		}

		if hexInput {
			data, err = decodeHexInput(data)
			if err != nil {
				log.Fatalf("input contains invalid hex data: %v", err)
			}
		}

		// Size is always for the uncompressed data, set it before compressing
		frag.Size = int64(len(data))

		if compression {
			data, err = compress(data)
			if err != nil {
				log.Fatalf("failed to compress data: %v", err)
			}
		}

		frag.RawData = data
		os.Stdout.WriteString(frag.String())

	default:
		log.Fatalf("unknown mode: %s", mode)
	}
}

func decodeHexInput(input []byte) ([]byte, error) {
	var err error
	var data []byte
	for line := range bytes.Lines(input) {
		line := bytes.Map(dropSpaces, line)
		if len(line) == 0 || line[0] == '#' {
			continue
		}
		data, err = hex.AppendDecode(data, line)
		if err != nil {
			return data, err
		}
	}
	return data, nil
}

func dropSpaces(r rune) rune {
	if unicode.IsSpace(r) {
		return -1
	}
	return r
}
