name: Go
on:
  pull_request:
  push:
    branches: [master]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        run: golangci-lint run

      - name: Test
        run: go test -v ./...

